---
- hosts: localhost
  gather_facts: false
  vars:
    namespace: test-ns
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Create a namespace
      kubernetes.core.k8s:
        host: https://api.nareshp.lab.psi.pnq2.redhat.com:6443
        username: kubeadmin
        password: SCkff-wqao2-fbP2U-ScxS2
        verify_ssl: false
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"
