---
- name: Check service status
  hosts: all
  tasks:
  - name: Get Service Status
    ansible.builtin.systemd:
      name: "sshd"
    register: pg_service_status

  - debug:
      var: pg_service_status.status.ActiveState
