---
- name: test centralised role
  hosts: all
    vars:
    namespace: test-ns
    kubeconfig_path: kubeconfig 
  tasks:
    - name: Login to Cluster
      openshift_login:
        username: admin
        password: admin
        server: http://api.crc-lgph7-master-0.crc.pf39gmx93kqp.instruqt.io:6443
#        certificate_authority: /path/to/openshift-cluster-ca.crt
      register: openshift_login

  
