---
- name: test centralised role
  hosts: all
  tasks:
    - name: Login to Cluster
      openshift_login:
        username: kubeadmin
        password: SCkff-wqao2-fbP2U-ScxS2
        server: https://api.apps.nareshp.lab.psi.pnq2.redhat.com:6443
#        certificate_authority: /path/to/openshift-cluster-ca.crt
      register: openshift_login

  
