---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        urls:
          - http://10.76.107.105:80
        delay: 10
        return_content: true

  rules:
    - name: Debug
      condition: event.url_check.status == "down"
    ## Define the action we should take should the condition be met  
      action:
        debug: "{{ event }}"
        

