---
- name: Local Test Runner Rules
  hosts: localhost
  sources:
    - ansible.eda.watchdog:
        path: "/demo"
        recursive: true
        ignore_regexes: ['.*\.pytest.*', '.*__pycache__.*', '.*/.git.*']
  rules:
    - name: run tests 1
      condition: event.type == "DirModifiedEvent"
      action:
        run_job_template:
          name: dir_modified
          organization: "Default"
    - name: run tests 2
      condition: event.type == "FileModifiedEvent"
      action:
        run_job_template:
          name: file_modified
          organization: "Default"
    - name: print output
      condition: event.output is defined
      action:
        print_event:
          var_root: output
...
