---
- name: Respond to github webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:
          data_alerts_path: alerts
          data_host_path: labels.instance
          data_path_separator: .
          skip_original_data: true
  rules:
    - name: SELinux was disabled
      condition: event.alert.status == "firing" 
      action:
        run_job_template:
          name: Apply_baseline
          organization: Default
    - name: get prometheus alerts
      condition: event.payload is defined
      action:
        debug: "{{ event.payload }}"
