---
- name: Site Down
  hosts: all
  gather_facts: false
  become: true
  
  tasks:
    - name: url output
#      uri: 
#        url: http://10.76.107.105:80
#        return_content: true
      debug:
        msg: "Website is down!"
    - name: Restart service
      ansible.builtin.systemd_service:
        state: restarted
        name: httpd
    - name: Replace website
      copy:
        remote_src: yes
        src: /tmp/index.html
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '0644'
      
