---
- name: Site is up
  hosts: all
  gather_facts: false
  tasks:
    - name: url output
      uri: 
        url: http://10.76.107.105:80
        return_content: true
    - debug:
        msg: "All is up and well"
